# Generated by Django 3.0.3 on 2021-02-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subscription_expired',
            new_name='email_authenticated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed_payment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
