# Generated by Django 3.0.3 on 2020-06-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
