# Generated by Django 3.0.3 on 2020-06-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
