# Generated by Django 3.0.3 on 2020-08-04 15:53

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200613_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AlterField(
            model_name='category',
            name='details',
            field=models.CharField(default='Default', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='dropoff_point',
            field=models.TextField(blank=True, choices=[('Uniben', (('HALL4', 'Hall4'), ('HALL3', 'Hall3'), ('HALL2', 'Hall2'), ('HALL1', 'Hall1'), ('Main Gate', 'Main gate'), ('Green Park', 'Green Park'), ('GTBANK', 'GTBank Wifi Spot'), ('NAAS Garden', 'Naas Garden'), ('Physical Science Complex', 'Physical Science Complex'), ('Med Complex', 'Medical Science Complex'), ('Basement', 'Basement'), ('JUNE12', 'June12'), ('Engineering Park', 'Engineering Park')))], default='Main Gate', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='exchange_for',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='alias',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OnlineStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ratings', models.FloatField(blank=True, default=0, max_length=5, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='online_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.OnlineStore'),
        ),
    ]
