# Generated by Django 3.0.3 on 2020-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200804_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinestore',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
