# Generated by Django 3.0.3 on 2020-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200601_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exchange_for',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
